---
- name: macOS Configuration
  hosts: localhost
  connection: local
  tasks:
    - name: Execute .osx configuration script
      ansible.builtin.shell: |
        chmod +x ~/.osx
        ~/.osx
      args:
        executable: /bin/bash
      register: script_output

    - name: Display script output
      ansible.builtin.debug:
        var: script_output.stdout
