---
- name: Apply macOS Settings with Ansible
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Ensure .osx configuration script is executable
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.osx"
        mode: '0755'
        state: file

    - name: Execute .osx configuration script
      ansible.builtin.command: "{{ lookup('env', 'HOME') }}/.osx"
      args:
        chdir: "{{ lookup('env', 'HOME') }}"
      register: result
      ignore_errors: true

    - name: Display output of .osx script execution
      debug:
        var: result.stdout_lines
