---
- name: Apply macOS Settings with Ansible
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Ensure the repository is cloned to the user's home directory
      ansible.builtin.git:
        repo: "https://github.com/hsolon/ansible_desktop.git"
        dest: "{{ lookup('env', 'HOME') }}/ansible_desktop"
        version: feature/role-based-setup
        update: yes

    - name: Ensure .osx configuration script is executable
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/ansible_desktop/.osx"
        mode: '0755'
        state: file

    - name: Execute .osx configuration script
      ansible.builtin.command: "{{ lookup('env', 'HOME') }}/ansible_desktop/.osx"
      args:
        chdir: "{{ lookup('env', 'HOME') }}/ansible_desktop"
      register: result
      ignore_errors: true

    - name: Display output of .osx script execution
      debug:
        var: result.stdout_lines
