---
- name: Apply Gaming Configuration for macOS
  hosts: localhost
  connection: local
  become: true
  tasks:

    # Install Discord
    - name: Install Discord using Homebrew Cask
      homebrew_cask:
        name: discord
        state: present

    # Install Google Chrome
    - name: Install Google Chrome using Homebrew Cask
      homebrew_cask:
        name: google-chrome
        state: present

    # Install Roblox
    - name: Install Roblox using Homebrew Cask
      homebrew_cask:
        name: roblox
        state: present

    # Install WireGuard from the App Store
    - name: Install WireGuard using mas-cli (Mac App Store)
      community.general.mas:
        id: 1451685025  # Replace with the correct App Store ID for WireGuard
        state: present
        become: true

    # Install Strongbox Pro from the App Store
    - name: Install Strongbox Pro using mas-cli (Mac App Store)
      community.general.mas:
        id: 1500040999  # Replace with the correct App Store ID for Strongbox Pro
        state: present
        become: true
