---
- hosts: localhost
  connection: local
  become: false  # if true, allows sudo to root

  tasks:
    - name: install wget using homebrew (force ARM)
      command: arch -arm64 /opt/homebrew/bin/brew install wget
