---
- hosts: localhost
  connection: local
  become: false

  tasks:
    # Dock Configurations
    - name: Remove Dock autohide delay
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide-delay
        type: float
        value: 0

    - name: Speed up Dock autohide animation
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide-time-modifier
        type: int
        value: 0

    - name: Add spacer tile to Dock
      ansible.builtin.shell: |
        defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}'
      args:
        executable: /bin/bash

    - name: Set Dock position to left
      community.general.osx_defaults:
        domain: com.apple.dock
        key: orientation
        type: string
        value: "left"

    - name: Disable Dock minimize/maximize animation
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mineffect
        type: string
        value: "scale"

    - name: Enable auto-hide for the Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true

    - name: Disable Dock animate opening applications
      community.general.osx_defaults:
        domain: com.apple.dock
        key: launchanim
        type: bool
        value: false

    - name: Disable Dock show recent applications
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false

    - name: Restart Dock to apply changes
      ansible.builtin.command: killall Dock

    # Finder Configurations
    - name: Show all filename extensions in Finder
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true

    - name: Remove Tags from Finder sidebar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowRecentTags
        type: bool
        value: false

    - name: Hide Recents from Finder sidebar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowRecentDocuments
        type: bool
        value: false

    - name: Enable Finder status bar to show full path at the bottom
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowStatusBar
        type: bool
        value: true
    
    - name: Show full POSIX path in Finder window title
      community.general.osx_defaults:
        domain: com.apple.finder
        key: _FXShowPosixPathInTitle
        type: bool
        value: true


    - name: Set Finder view to List view by default
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXPreferredViewStyle
        type: string
        value: "Nlsv"

    # Restart Finder to apply changes
    - name: Restart Finder to apply changes
      ansible.builtin.command: killall Finder
