---
- hosts: localhost
  connection: local
  become: false

  tasks:
    # Finder: Show all filename extensions
    - name: Show all filename extensions in Finder
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true

    # Finder: Remove Tags from sidebar
    - name: Remove Tags from Finder sidebar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowRecentTags
        type: bool
        value: false

    # Finder: Hide Recents from the sidebar
    - name: Hide Recents from Finder sidebar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXPreferredGroupBy
        type: string
        value: "None"

    # Finder: Show full path in Finder window titles
    - name: Show full POSIX path in Finder window title
      community.general.osx_defaults:
        domain: com.apple.finder
        key: _FXShowPosixPathInTitle
        type: bool
        value: true

    # Restart Finder to apply changes
    - name: Restart Finder to apply changes
      ansible.builtin.command: killall Finder
