---
- hosts: localhost
  connection: local
  become: false

  tasks:
    # Dock configurations
    - name: Remove Dock autohide delay
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide-delay
        type: float
        value: 0
      # This removes the delay when auto-hiding the Dock, making it appear instantly.

    - name: Speed up Dock autohide animation
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide-time-modifier
        type: int
        value: 0
      # This speeds up the animation for the Dock when it auto-hides.

    - name: Set Dock position to left
      community.general.osx_defaults:
        domain: com.apple.dock
        key: orientation
        type: string
        value: "left"
      # Positions the Dock on the left side of the screen.

    - name: Disable Dock minimize/maximize animation
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mineffect
        type: string
        value: "scale"
      # Disables animation for minimizing/maximizing apps in the Dock.

    - name: Enable auto-hide for the Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
      # Enables auto-hide for the Dock.

    - name: Disable Dock animate opening applications
      community.general.osx_defaults:
        domain: com.apple.dock
        key: launchanim
        type: bool
        value: false
      # Disables the animation for applications opening from the Dock.

    - name: Disable Dock show recent applications
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false
      # Removes the "Recent Applications" section from the Dock.

    - name: Speed up Mission Control animation duration
      community.general.osx_defaults:
        domain: com.apple.dock
        key: expose-animation-duration
        type: float
        value: 0.15
      # Speeds up the animations when switching between apps in Mission Control.

    - name: Restart Dock to apply changes
      ansible.builtin.command: killall Dock
      # Restarts the Dock to apply all configuration changes made above.

    # Finder configurations
    - name: Show all filename extensions in Finder
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true
      # Configures Finder to always display file extensions.

    - name: Remove Tags from Finder sidebar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowRecentTags
        type: bool
        value: false
      # Removes the "Tags" section from the Finder sidebar.

    - name: Hide Recents from Finder sidebar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXPreferredGroupBy
        type: string
        value: "None"
      # Hides "Recents" from appearing in the Finder sidebar under Favorites.

    - name: Show full POSIX path in Finder window title
      community.general.osx_defaults:
        domain: com.apple.finder
        key: _FXShowPosixPathInTitle
        type: bool
        value: true
      # Displays the full path for the current directory in Finder's title bar.

    - name: Show Finder status bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowPathBar
        type: bool
        value: true
      # Enables the status bar at the bottom of Finder windows.

    - name: Set Home directory as default location for new Finder windows
      community.general.osx_defaults:
        domain: com.apple.finder
        key: NewWindowTarget
        type: string
        value: "PfLo"
      # Sets the default folder for new Finder windows to a custom path.

    - name: Set Home directory path for new Finder windows
      community.general.osx_defaults:
        domain: com.apple.finder
        key: NewWindowTargetPath
        type: string
        value: "file://{{ ansible_env.HOME }}/"
      # Specifies the actual path for new Finder windows, here set to the user's Home directory.

    - name: Set Finder default view style to List view
      community.general.osx_defaults:
        domain: com.apple.finder
        key: FXPreferredViewStyle
        type: string
        value: Nlsv
      # Sets the default Finder view mode to List view.

    # # Finder sidebar configurations
    # - name: Modify Finder sidebar preferences
    #   ansible.builtin.command: |
    #     defaults write com.apple.sidebarlists favoritesitems -array \
    #       '{ "Name" = "Desktop"; "Visibility" = "Always"; }' \
    #       '{ "Name" = "Documents"; "Visibility" = "Always"; }' \
    #       '{ "Name" = "Downloads"; "Visibility" = "Always"; }' \
    #       '{ "Name" = "Movies"; "Visibility" = "Always"; }' \
    #       '{ "Name" = "Music"; "Visibility" = "Always"; }' \
    #       '{ "Name" = "Pictures"; "Visibility" = "Always"; }' \
    #       '{ "Name" = "Home"; "Visibility" = "Always"; }'
    #   ignore_errors: true
    #   register: sidebar_config
    #   # Configures the sidebar to show or hide specific folders like Movies, Pictures, and Home, while hiding Recents.

    - name: Restart Finder to apply changes
      ansible.builtin.command: killall Finder
      # Restarts Finder to apply all configuration changes made above.

    # Other configurations
    - name: Set screenshots location to Downloads
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: "{{ ansible_env.HOME }}/Downloads"
      # Sets the default location for screenshots to the Downloads folder.

    - name: Set screenshots format to JPG
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: type
        type: string
        value: "jpg"
      # Sets the screenshot file format to JPG.

    - name: Prevent .DS_Store files on network volumes
      community.general.osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true
      # Disables .DS_Store files creation on network volumes.

    - name: Disable automatic spell check
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false
      # Disables automatic spell check.

    - name: Disable natural scrolling for mouse
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: false
      # Disables natural scrolling direction for the mouse.
