---
- name: Set screenshots location to Downloads
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_env.HOME }}/Downloads"

- name: Set screenshots format to JPG
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: "jpg"
