---
- name: Install base utilities
  homebrew:
    name: "{{ item }}"
  with_items:
    - m-cli
    - dockutil

# Remove all items from the Dock
- name: Remove all items from the Dock
  command: dockutil --remove all
  ignore_errors: true  # Prevent failure if the Dock is already empty

# Add desired applications to the Dock
- name: Add Finder to the Dock
  command: dockutil --add /System/Library/CoreServices/Finder.app --position 1

- name: Add Launchpad to the Dock
  command: dockutil --add /Applications/Launchpad.app --position 2

- name: Add Safari to the Dock
  command: dockutil --add /Applications/Safari.app --position 3

- name: Add Mail to the Dock
  command: dockutil --add /Applications/Mail.app --position 4

- name: Add Photos to the Dock
  command: dockutil --add /Applications/Photos.app --position 5

- name: Add Settings to the Dock
  command: dockutil --add /Applications/System\ Preferences.app --position 6

- name: Add App Store to the Dock
  command: dockutil --add /Applications/App\ Store.app --position 7

- name: Add Terminal to the Dock
  command: dockutil --add /Applications/Utilities/Terminal.app --position 8

- name: Remove Dock autohide delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  # This removes the delay when auto-hiding the Dock, making it appear instantly. One of thes should work.

- name: Speed up Dock autohide animation
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: int
    value: 0
  # This speeds up the animation for the Dock when it auto-hides.

- name: Set Dock position to left
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: "left"
  # Positions the Dock on the left side of the screen.

- name: Disable Dock minimize/maximize animation
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: "scale"
  # Disables animation for minimizing/maximizing apps in the Dock.

- name: Enable auto-hide for the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  # Enables auto-hide for the Dock.

- name: Disable Dock animate opening applications
  community.general.osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: false
  # Disables the animation for applications opening from the Dock.

- name: Disable Dock show recent applications
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
  # Removes the "Recent Applications" section from the Dock.

- name: Speed up Mission Control animation duration
  community.general.osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.15
  # Speeds up the animations when switching between apps in Mission Control

    

# ... Add remaining Dock tasks here ...

- name: Restart Dock to apply changes
  ansible.builtin.command: killall Dock
