---
- name: Show all filename extensions in Finder
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  # Configures Finder to always display file extensions.

- name: Remove Tags from Finder sidebar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    type: bool
    value: false
  # Removes the "Tags" section from the Finder sidebar.

- name: Hide Recents from Finder sidebar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredGroupBy
    type: string
    value: "None"
  # Hides "Recents" from appearing in the Finder sidebar under Favorites.

- name: Show full POSIX path in Finder window title
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
  # Displays the full path for the current directory in Finder's title bar.

- name: Show Finder status bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
  # Enables the status bar at the bottom of Finder windows.

- name: Set Home directory as default location for new Finder windows
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfLo"
  # Sets the default folder for new Finder windows to a custom path.

- name: Set Home directory path for new Finder windows
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://{{ ansible_env.HOME }}/"
  # Specifies the actual path for new Finder windows, here set to the user's Home directory.

- name: Set Finder default view style to List view
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv
  # Sets the default Finder view mode to List view.

# Finder sidebar configurations
- name: Modify Finder sidebar preferences
  ansible.builtin.command: |
    defaults write com.apple.sidebarlists favoritesitems -array \
      '{ "Name" = "Desktop"; "Visibility" = "Always"; }' \
      '{ "Name" = "Documents"; "Visibility" = "Always"; }' \
      '{ "Name" = "Downloads"; "Visibility" = "Always"; }' \
      '{ "Name" = "Movies"; "Visibility" = "Always"; }' \
      '{ "Name" = "Music"; "Visibility" = "Always"; }' \
      '{ "Name" = "Pictures"; "Visibility" = "Always"; }' \
      '{ "Name" = "Home"; "Visibility" = "Always"; }'
  ignore_errors: true
  register: sidebar_config
  # Configures the sidebar to show or hide specific folders like Movies, Pictures, and Home, while hiding Recents.


# ... Add remaining Finder tasks here ...

- name: Restart Finder to apply changes
  ansible.builtin.command: killall Finder
