---
- name: Install and configure Homebrew autoupdate
  hosts: localhost
  tasks:
    - name: Tap DomT4/autoupdate repository
      command: brew tap domt4/autoupdate
      args:
        creates: /opt/homebrew/Library/Taps/domt4/homebrew-autoupdate

    - name: Install Homebrew autoupdate
      command: brew install autoupdate
      args:
        creates: /opt/homebrew/bin/brew-autoupdate

    - name: Start Homebrew autoupdate
      command: brew autoupdate start 43200 --upgrade --cleanup --immediate --sudo
