---
- name: Configure Homebrew Autoupdate
  tasks:
    - name: Tap DomT4/autoupdate repository
      community.general.homebrew_tap:
        name: domt4/autoupdate
        state: present

    - name: Install Homebrew autoupdate
      community.general.homebrew:
        name: autoupdate
        state: present

    - name: Start Homebrew autoupdate
      command: brew autoupdate start 43200 --upgrade --cleanup --immediate --sudo
