---
- name: Prevent .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  # Disables .DS_Store files creation on network volumes.

- name: Disable automatic spell check
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
  # Disables automatic spell check.

- name: Disable natural scrolling for mouse
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
  # Disables natural scrolling direction for the mouse.

- name: Restart Finder to apply changes
  ansible.builtin.command: killall Finder